=== lsuits/lsu_xml_enrollment_provider/sample_enrollment/SEMESTERS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="rows">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="ROW" type="rowType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="rowType">
        <xs:all>
            <xs:element name="YEAR" type="xs:gYear"/>
            <xs:element name="NAME" type="nonEmptyString"/>
            <xs:element name="CAMPUS" type="nonEmptyString"/>
            <xs:element name="SESSION_KEY" type="xs:string"/>
            <!-- Note that UES is selective about the semesters it processses -->
            <!-- Especially, it will not process semesters whose grade_due    -->
            <!-- value is less than now().                                    -->
            <xs:element name="CLASSES_START" type="xs:unsignedInt"/>
            <xs:element name="GRADES_DUE" type="xs:unsignedInt"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="nonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== lsuits/lsu_xml_enrollment_provider/sample_enrollment/SEMESTERS.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rows xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="SEMESTERS.xsd">
  <ROW>
    <YEAR>2014</YEAR>
    <NAME>Some Semester</NAME>
    <CAMPUS>Main Campus</CAMPUS>
    <SESSION_KEY></SESSION_KEY>
    <CLASSES_START>1401580800</CLASSES_START>
    <GRADES_DUE>1409529600</GRADES_DUE>
  </ROW>
</rows>
